language: nodes_js

node_js:
    - '5.4.1'

before_install:
    - echo "Before Install..."
    
install:
    - echo "Installing..."
    
before_script:
    - echo "Before script..."
    
script:
    - echo "Script..."
    
after_script:
    - echo "After script..."