language: node_js
node_js:
    - 4.4.0
env:
    - SITE=github-travis-poc2 BRANCH=master
#    - SITE=github-travis-poc2-dev BRANCH=dev

# Limit Travis Builds to only master and dev branch
branches:
    only:
        - master
#        - dev

before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

#install:
before_script:
    - npm install
    - gulp dist
    
script: 
    - node_modules/karma/bin/karma start karma-js.conf.js --single-run
    - gulp e2e
    
#after_success or after_failure

before_deploy:
    - ./scripts/travis/before_deploy.sh
    
deploy:
    provider: azure_web_apps
    skip_cleanup: true
    site: $SITE
    #on:
    #    branch: $BRANCH
    #    condition: $TRAVIS_BRANCH = $BRANCH

#after_deploy
#after_script