language: nodes_js

node_js:
    - '5.4.1'

before_install:
    - echo "Before Install..."
    
install:
    - echo "Installing..."
    - npm install -g karma
    - npm install    
    
before_script:
    #  For Firefox Karma Tests
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sleep 5
    - karma start --browsers Firefox --single-run
    
script:
    - echo "Script..."
    
after_script:
    - echo "After script..."