language: nodes_js

node_js:
    - '5.4.1'

#before_install:
    - echo "Before Install..."
    
#install:
#    - echo "Installing..."
#    - npm install -g karma
#    - npm install    

script: node_modules/karma/bin/karma start karma-js.conf.js --single-run
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
before_script:
    - npm install

#before_script:
    #  For Firefox Karma Tests
    #- export DISPLAY=:99.0
    #- sh -e /etc/init.d/xvfb start
    #- sleep 5
    #- karma start --browsers Firefox --single-run
    
#script:
   # - echo "Script..."
    
#after_script:
 #   - echo "After script..."